'download --all' no longer uses browser; downloads directly

diff --git a/filebiner b/filebiner
--- a/filebiner
+++ b/filebiner
@@ -42,7 +42,7 @@ uploadfile() {
     fi
     # if text being uploaded via pipe and FILE_NAME is empty, set random file name
     if [[  "$UPLOAD_FILE" == "-" ]] && [[ -z "$FILE_NAME" ]]; then
-        FILE_NAME="paste-$RANDOM.txt"
+        FILE_NAME="$(date +%s).txt"
     # else get file name using rev and cut if FILE_NAME is empty
     elif [[ -z "$FILE_NAME" ]]; then
             FILE_NAME="$(echo "$UPLOAD_FILE" | rev | cut -f1 -d'/' | rev)"
@@ -116,7 +116,6 @@ downloadfile() {
     fi
     exit 0
 }
-# Figure out how to make this work without opening browser
 # download all files from a bin on filebin.net
 downloadall() {
     for DLAARG in "$@"; do
@@ -131,20 +130,31 @@ downloadall() {
     if [[ -z "$BIN_NAME" ]]; then
         BIN_NAME="$USER"
     fi
-    echo "Opening 'https://filebin.net/archive/"$BIN_NAME"/tar' with 'xdg-open'..."
-    xdg-open "https://filebin.net/archive/"$BIN_NAME"/tar"
     # set FILE_NAME to $USER if empty
-#     if [[ -z "$FILE_NAME" ]]; then
-#         FILE_NAME="$HOME/Downloads/$USER"
-#     else
-#         FILE_NAME="$(readlink -f "$FILE_NAME")"
-#     fi
-#     if [[ ! -d "$(dirname "$FILE_NAME")" ]]; then
-#         echo "Directory '$(dirname "$FILE_NAME")' does not exist!"
-#         exit 1
-#     fi
-#     curl -o "$FILE_NAME.tar" https://filebin.net/archive/"$BIN_NAME"/tar || { echo "Failed to download 'https://filebin.net/$BIN_NAME'"; exit 1; }
-#     echo "$BIN_NAME saved to $FILE_NAME.tar"
+    if [[ -z "$FILE_NAME" ]]; then
+        FILE_NAME="$HOME/Downloads/$USER.tar"
+    # else find real path of input
+    else
+        FILE_NAME="$(readlink -f "$FILE_NAME")"
+    fi
+    # exit if directory doesn't exist
+    if [[ ! -d "$(dirname "$FILE_NAME")" ]]; then
+        echo "Directory '$(dirname "$FILE_NAME")' does not exist!"
+        exit 1
+    fi
+    # add tar extension if missing
+    if [[ ! "$FILE_NAME" =~ ".tar" ]]; then
+        FILE_NAME=""$FILE_NAME".tar"
+    fi
+    # get temp key for downloading archive
+    TEMP_KEY="$(curl -s https://filebin.net/archive/"$BIN_NAME"/tar | grep '?t' | cut -f2 -d'"')"
+    if [[ -z "$TEMP_KEY" ]]; then
+        echo "Failed to download 'https://filebin.net/$BIN_NAME'"
+        exit 1
+    fi
+    # download using temp key with curl
+    curl -o "$FILE_NAME" https://filebin.net/archive/"$BIN_NAME"/tar"$TEMP_KEY" || { echo "Failed to download 'https://filebin.net/$BIN_NAME'"; exit 1; }
+    echo "$BIN_NAME saved to $FILE_NAME"
     exit 0
 }
 # delete a file from filebin.net
@@ -179,7 +189,7 @@ deletefile() {
 }
 # show filebiner help
 filebinerhelp() {
-printf "filebiner v0.0.1 - https://www.simonizor.net
+printf "filebiner v0.0.2 - https://www.simonizor.net
 Uploads and manages files on https://filebin.net
 
 Usage: filebiner <argument> [subarguments]
